# =============================================
# Oracle DB
# 사용 시 application.properties의
# spring.autoconfigure.exclude 줄 제거 필요
# =============================================
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/XE
spring.datasource.username=여기에_DB_유저명
spring.datasource.password=여기에_DB_비밀번호
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=1800000
spring.datasource.hikari.connection-test-query=SELECT 1 FROM DUAL
